### ISSUE TITLE
setup of new cython modules does not work properly?

### ISSUE THREAD

**Issue by Kostis-S-Z** [learnables/learn2learn#111]
Great to see the addition of Cython modules in the building of datasets!

However, I seem to have a bit of a problem. When I try to execute maml_miniimagenet.py (or cifarfs.py or fc100.py or probably any other script that makes use of the data modules) without already having a copy of the datasets locally I get the following error.

```
Traceback (most recent call last):
  File ".../learn2learn/learn2learn/vision/datasets/cifarfs.py", line 11, in <module>
    from learn2learn.data.utils import download_file_from_google_drive
  File ".../learn2learn/learn2learn/__init__.py", line 4, in <module>
    from . import data
  File ".../learn2learn/learn2learn/data/__init__.py", line 3, in <module>
    from . import transforms
ImportError: cannot import name 'transforms'
``` 

**I did run the setup.py again** in order to build the modules, but it still didn't work (In fact, I made a new virtual env to try from scratch, but I still get that error). Any ideas?

**Comment by Kostis-S-Z** [comment]
Hmm actually I think this bug is still there... I tried again from scratch:

1. clone repo
2. create new venv
3. `pip install learn2learn `

then `run maml_miniimagenet.py` gives `ImportError: cannot import name 'transforms').`

I realised that during `pip install learn2learn`, Cython is not actually installed.

The simplest solution that works is that before `pip install learn2learn`, you do `pip install cython`. I am not sure if there is a way to install cython automatically since it is a dependency of the setuptools itself. @ https://stackoverflow.com/a/56009658

So a quick solution would be to add to readme that cython needs to be install before l2l.

1. clone repo
2. create new venv
3. `pip install cython`
4. `pip install learn2learn `
