### ISSUE TITLE
Can't save protonet example model

### ISSUE THREAD

**Issue by hanxuanhuo** [learnables/learn2learn#182]
I try to save checkpoint using protonet_miniimagenet.py by adding this at the end:
```
if epoch % 1 == 0:
            if not os.path.exists('checkpoints/protonet'):
                os.makedirs('checkpoints/protonet')
            torch.save(model, 'checkpoints/protonet/epoch_{}.pth'.format(epoch))   
```
but I failed and get this information:
```
Traceback (most recent call last):
  File "protonet_miniimagenet.py", line 198, in <module>
    torch.save(model, 'checkpoints/protonet/epoch_{}.pth'.format(epoch))
  File "/home/rlf/ve3/lib/python3.6/site-packages/torch/serialization.py", line 370, in save
    _legacy_save(obj, opened_file, pickle_module, pickle_protocol)
  File "/home/rlf/ve3/lib/python3.6/site-packages/torch/serialization.py", line 443, in _legacy_save
    pickler.dump(obj)
AttributeError: Can't pickle local object 'ConvBlock.__init__.<locals>.<lambda>'
```

**Comment by seba-1511** [comment]
Hello @hanxuanhuo, 

Sorry for the delayed response -- hopefully you've been able to find a solution. In the meantime, this is now automatically done with the Lightning wrappers merged in #202 .
