### ISSUE TITLE
Can l2l work in win10？

### ISSUE THREAD

**Issue by yaoxunji** [learnables/learn2learn#184]
I use win10 to run rl.example and got a trouble,such as
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Anaconda\envs\mujoco_plus\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "D:\Anaconda\envs\mujoco_plus\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
  File "D:\Anaconda\envs\mujoco_plus\lib\site-packages\cherry\envs\base.py", line 56, in __getattr__
    return getattr(self.env, attr)
  File "D:\Anaconda\envs\mujoco_plus\lib\site-packages\cherry\envs\base.py", line 56, in __getattr__
    return getattr(self.env, attr)
  File "D:\Anaconda\envs\mujoco_plus\lib\site-packages\cherry\envs\base.py", line 56, in __getattr__
    return getattr(self.env, attr)
  [Previous line repeated 329 more times]
RecursionError: maximum recursion depth exceeded while calling a Python object
what should I do ?

**Comment by seba-1511** [comment]
Are you able to run multi-processing Mujoco environments (without L2L or cherry) on Windows?

**Comment by seba-1511** [comment]
Inactive.
