### ISSUE TITLE
Example news_topic_classification.py does not seem to work

### ISSUE THREAD

**Issue by versae** [learnables/learn2learn#198]
Fascinating library. I tried to run the example in `news_topic_classification.py` using a Colab but unfortunately it always fails at exactly the same point:
```
!wget https://raw.githubusercontent.com/learnables/learn2learn/master/examples/text/news_topic_classification.py
!python news_topic_classification.py --download-location $(pwd)
```
And the output (omitting some pats)
```
--2020-10-30 15:38:36--  https://raw.githubusercontent.com/learnables/learn2learn/master/examples/text/news_topic_classification.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7828 (7.6K) [text/plain]
Saving to: ‘news_topic_classification.py’

news_topic_classifi 100%[===================>]   7.64K  --.-KB/s    in 0s      

2020-10-30 15:38:36 (79.2 MB/s) - ‘news_topic_classification.py’ saved [7828/7828]

Downloading: "https://github.com/pytorch/fairseq/archive/master.zip" to /content/master.zip
fatal: not a git repository (or any of the parent directories): .git
running build_ext (NOT SURE WHY IT'S BUILDING fairseq)
[...]
Loss : 2.015 Acc : 0.175:   7% 67/1000 [03:04<43:06,  2.77s/it]Traceback (most recent call last):
  File "news_topic_classification.py", line 208, in <module>
    download_location=args.download_location)
  File "news_topic_classification.py", line 153, in main
    batch=shots * ways)
  File "news_topic_classification.py", line 74, in compute_loss
    _BatchedDataset(task), batch_size=batch, shuffle=True, num_workers=0)):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 475, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/collate.py", line 83, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/collate.py", line 83, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/collate.py", line 67, in default_collate
    return torch.tensor(batch, dtype=torch.float64)
TypeError: must be real number, not str
Loss : 2.015 Acc : 0.175:   7% 67/1000 [03:06<43:12,  2.78s/it]
```
I also tried with my own `Dataset` but got the same error, just at a different point. Also tried updating PyTorch to 1.7 but still nothing. I'm sure I am missing something and would really appreciate any pointers.

Cheers.

**Comment by seba-1511** [comment]
Hi @versae ,

Thanks for opening the issue. The news classification example might be out of date, are you running into similar issues with other examples?

**Comment by versae** [comment]
Thanks for the quick reply! It's the only one I've tried because it's the kind of experiment I'm also working on.

I would understand if so if you folks have no bandwidth to fix it `learn2learn` looks like a really easy way to try out different approaches, , could you point me to a version of the library that makes it work?

**Comment by versae** [comment]
Any update on this?

**Comment by seba-1511** [comment]
Not as far as I know; the closest solution seems to be along the lines of #187. The version that might have worked with the news classification tasks was pre-0.1.0.

**Comment by versae** [comment]
I see. Thanks!
