### ISSUE TITLE
MAML-RL codes don't exit on completion on a server

### ISSUE THREAD

**Issue by SapanaChaudhary** [learnables/learn2learn#298]
The codes in examples/rl/ don't exit on completion on a server. I need to explicitly do Ctrl+C for the code to exit. It looks like the python subprocess is hanging. This is true for the other maml variants as well. What should I do to make the code exit without the keyboard interrupt? 

Here is the error message on pressing Ctrl+C: 

^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/grads/s/sapanac/anaconda3/envs/learn-2-learn/lib/python3.7/multiprocessing/util.py", line 300, in _run_finalizers
    finalizer()
  File "/home/grads/s/sapanac/anaconda3/envs/learn-2-learn/lib/python3.7/multiprocessing/util.py", line 224, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/home/grads/s/sapanac/anaconda3/envs/learn-2-learn/lib/python3.7/multiprocessing/queues.py", line 192, in _finalize_join
    thread.join()
  File "/home/grads/s/sapanac/anaconda3/envs/learn-2-learn/lib/python3.7/threading.py", line 1044, in join
    self._wait_for_tstate_lock()
  File "/home/grads/s/sapanac/anaconda3/envs/learn-2-learn/lib/python3.7/threading.py", line 1060, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
Traceback (most recent call last):
  File "multiple_exps/dense_mult_exps_demo_10.py", line 21, in <module> 
    p = subprocess.run(["python", cmd]) #, arg1, arg2, arg3, arg4, arg5])
  File "/home/grads/s/sapanac/anaconda3/envs/learn-2-learn/lib/python3.7/subprocess.py", line 490, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/home/grads/s/sapanac/anaconda3/envs/learn-2-learn/lib/python3.7/subprocess.py", line 956, in communicate
    self.wait()
  File "/home/grads/s/sapanac/anaconda3/envs/learn-2-learn/lib/python3.7/subprocess.py", line 1019, in wait
    return self._wait(timeout=timeout)
  File "/home/grads/s/sapanac/anaconda3/envs/learn-2-learn/lib/python3.7/subprocess.py", line 1653, in _wait
    (pid, sts) = self._try_wait(0)
  File "/home/grads/s/sapanac/anaconda3/envs/learn-2-learn/lib/python3.7/subprocess.py", line 1611, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt

**Comment by seba-1511** [comment]
Hello @SapanaChaudhary,

Are you using the multi-processing (async) versions of the vectorized environments? Could you try without `AsyncVectorEnv` and see if the scripts exit properly?

**Comment by SapanaChaudhary** [comment]
Hi @seba-1511 , 

Yes, I am using multi-processing (async) versions of the vectorized environments. I am assuming multi-processing is the only way to use vectorized envs or am I wrong? 

The codes do indeed exit without using AsyncVectorEnv. 

Could there be a way to make the codes exit while retaining the multi-processing functionality?  (On short horizon problems, I get a 40-45 minutes speedup while using multi-processing. This number is larger on long horizon problems.)

I had tried the following without success: 
1. Force exit the code using: 

sys.exit(0)
os._exit(0)

2. Use subprocess to run the code. Get process ID, kill the process and give Ctrl+C signal: 

p = subprocess.run(["python", cmd]) 
pid = p.pid
os.kill(pid, signal.SIGINT)
p.send_signal(signal.SIGINT)

3. Set OMP_NUM_THREADS = 1 in l2l.gym.async_vec_env:

os.environ["OMP_NUM_THREADS"] = "1"


Thank you

**Comment by seba-1511** [comment]
Correct, unfortunately we don't have a non-async version of vectorized environments.

I would have also tried your solution 1., too bad it didn't work (maybe try with `exit(0)` or `quit(0)`?). In this case, does the main process exit but the child processes become zombies?

Could you try [`env.close()`](https://github.com/learnables/learn2learn/blob/992c95634c16c9a13a081cee633cb8d6f526e7b1/learn2learn/gym/envs/subproc_vec_env.py#L104) at the end of training? It should send a termination signal to child processes.

**Comment by SapanaChaudhary** [comment]
The code exists with env.close(), thanks :)
