### ISSUE TITLE
Debug

### ISSUE THREAD

**Issue by swaggyP9527** [learnables/learn2learn#354]
I get this error when I  run the maml_miniimagenet.py.
Traceback (most recent call last):
  File "C:\xxx\maml_miniimagenet.py", line 157, in <module>
    main()
  File "C:\xxx\maml_miniimagenet.py", line 75, in main
    tasksets = l2l.vision.benchmarks.get_tasksets('mini-imagenet',
  File "C:\xxx\learn2learn\vision\benchmarks\__init__.py", line 101, in get_tasksets
    datasets, transforms = _TASKSETS[name](train_ways=train_ways,
  File "C:\xxx\learn2learn\vision\benchmarks\mini_imagenet_benchmark.py", line 48, in mini_imagenet_tasksets
    train_dataset = l2l.vision.datasets.MiniImagenet(
  File "C:\xxx\learn2learn\vision\datasets\mini_imagenet.py", line 111, in __init__
    self.data = pickle.load(f)
_pickle.UnpicklingError: invalid load key, '<'.

**Comment by seba-1511** [comment]
See this issue: https://github.com/learnables/learn2learn/issues/310
