### ISSUE TITLE
Bug：TypeError: __init__() missing 2 required positional arguments: 'model_path' and 'frame_skip'

### ISSUE THREAD

**Issue by haoruili699** [learnables/learn2learn#407]
Hello，I am running learn2learn/gym/envs/mujoco/halfcheetah_forward_backward.py as a main function，and there is an error like this:
> Traceback (most recent call last):
  File ".../learn2learn/gym/envs/mujoco/halfcheetah_forward_backward.py", line 112, in <module>
    env = HalfCheetahForwardBackwardEnv()
  File ".../learn2learn/gym/envs/mujoco/halfcheetah_forward_backward.py", line 41, in __init__
    MetaEnv.__init__(self, task)
  File ".../learn2learn/gym/envs/meta_env.py", line 33, in __init__
    super(MetaEnv, self).__init__()
TypeError: __init__() missing 2 required positional arguments: 'model_path' and 'frame_skip'

I am running on Ubuntu 18.04, 
python==3.8 
gym==0.21.0
mujoco-py== 2.0.2.13
torch==1.11.0+cu113

I wonder how I can handle this error. Thank you for your reply!

**Comment by haoruili699** [comment]
I fix this error by using learn2learn==0.1.5. There may be some conflicts among the versions of mujopo-py, gym and learn2learn.
