### ISSUE TITLE
Issue with running learn2learn-master\examples\rl\maml_trpo.py

### ISSUE THREAD

**Issue by Gyn0802** [learnables/learn2learn#421]
D:\Anaconda\python.exe D:\py\learn2learn-master\examples\rl\maml_trpo.py 
D:\Anaconda\lib\site-packages\gym\spaces\box.py:73: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(
Traceback (most recent call last):
  File "D:\Anaconda\lib\site-packages\cherry\wrappers\base_wrapper.py", line 82, in __getattr__
Traceback (most recent call last):
  File "D:\Anaconda\lib\multiprocessing\connection.py", line 312, in _recv_bytes
    return getattr(self.env, attr)
  File "D:\Anaconda\lib\site-packages\cherry\wrappers\base_wrapper.py", line 82, in __getattr__
    return getattr(self.env, attr)
  File "D:\Anaconda\lib\site-packages\cherry\wrappers\base_wrapper.py", line 82, in __getattr__
    nread, err = ov.GetOverlappedResult(True)
    return getattr(self.env, attr)
BrokenPipeError  [Previous line repeated 996 more times]
  File "D:\Anaconda\lib\site-packages\cherry\wrappers\base_wrapper.py", line 79, in __getattr__
: [WinError 109] 管道已结束。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\py\learn2learn-master\examples\rl\maml_trpo.py", line 225, in <module>
    if attr in self.__dict__.keys():
RecursionError: maximum recursion depth exceeded while calling a Python object
    main()
  File "D:\py\learn2learn-master\examples\rl\maml_trpo.py", line 140, in main
    env = l2l.gym.AsyncVectorEnv([make_env for _ in range(num_workers)])
  File "D:\Anaconda\lib\site-packages\learn2learn\gym\async_vec_env.py", line 25, in __init__
    super(AsyncVectorEnv, self).__init__(env_fns, queue=self.queue)
  File "D:\Anaconda\lib\site-packages\learn2learn\gym\envs\subproc_vec_env.py", line 73, in __init__
    observation_space, action_space = self.remotes[0].recv()
  File "D:\Anaconda\lib\multiprocessing\connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "D:\Anaconda\lib\multiprocessing\connection.py", line 321, in _recv_bytes
    raise EOFError
EOFError

I encountered the above error when running the code in learn2learn-master\examples\rl\maml_trpo.py, and I'm not sure what the reason is. I suspect it might be related to the Cherry version. The Cherry version I have installed is 0.20.0. Who can  help me pinpoint the issue?

**Comment by ermengji** [comment]
do u figure out?
